In [219]:
from numpy import array

# Define basis vectors (also called "kets" in quantum mechanics)
ket0 = array([1, 0])
ket1 = array([0, 1])

# Here we divide each by 2 and then add
display(ket0 / 2 + ket1 / 2)

array([0.5, 0.5])

In [220]:
# Define two 2x2 matrices
M1 = array([[1, 1], [0, 0]])
M2 = array([[1, 1], [1, 0]])

# Add the two matrices after dividing each by 2
M1 / 2 + M2 / 2

array([[1. , 1. ],
       [0.5, 0. ]])

In [221]:
from numpy import matmul

# Multiply M1 with ket1
display(matmul(M1, ket1))

# Multiply M1 with M2
display(matmul(M1, M2))

# Multiply M2 with M1
display(matmul(M2, M1))

array([1, 0])

array([[2, 1],
       [0, 0]])

array([[1, 1],
       [1, 1]])

In [222]:
from qiskit.quantum_info import Statevector
from numpy import sqrt

# Define a balanced superposition state
u = Statevector([1 / sqrt(2), 1 / sqrt(2)])

# Define a state with complex amplitudes
v = Statevector([(1 + 2.0j) / 3, -2 / 3])

# Define another state (not normalized yet, so invalid!)
w = Statevector([1 / 3, 2 / 3])

print("State vectors u, v, and w have been defined.")

State vectors u, v, and w have been defined.


In [223]:
# Draw the state u in LaTeX form
display(u.draw("latex"))

# Draw the state v as plain text
display(v.draw("text"))

<IPython.core.display.Latex object>

[ 0.33333333+0.66666667j,-0.66666667+0.j        ]